name: cookiecutter-spatial-data-science

channels:
  - conda-forge

dependencies:
  - cookiecutter
  - pip
  - pip:
    - bump2version
    - mkdocs
    - mkdocs-glightbox
    - mkdocs-include-markdown-plugin
    - mkdocs-material
    - mkdocstrings[python]>=0.18
    - pytest-cookies
