name: {{ cookiecutter.conda_environment_name }}

channels:
  - esri
  - conda-forge

dependencies:
  - arcgis
  - arcpy
  - cookiecutter
  - deep-learning-essentials
  - dask
  - h3-py
  - jupyterlab
  - mkdocs
  - munch
  - nodejs
  - pip
  - progress
  - pylint
  - pypandoc
  - pytest
  - python
  - python-dotenv
  - pyyaml
  - scipy
  - scikit-learn
  - seaborn
  - shapely
  - swifter
  - tabulate
  - tqdm
  - pip:
    - azure-storage-blob
    - boto3
    - bump2version
    - ipykernel
    - placekey
    - pyarrow
    - sphinx
    - sphinx-autodoc-typehints
    - sphinx_rtd_theme
    - twine
