[build-system]
requires = ["setuptools>=61.0", "setuptools-scm>=8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "{{ cookiecutter.project_name }}"
version = "0.0.0"
authors = [
  { name="{{ cookiecutter.author_name }}"},
]
description = "{{ cookiecutter.description }}"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: Apache Software License",
]
{%- if cookiecutter.license == "Apache 2.0" -%}
license = "Apache-2.0"
{%- elif cookiecutter.license == "MIT" -%}
license = "MIT"
{%- elif cookiecutter.license == "BSD-3-Clause" -%}
license = "BSD-3-Clause"
{%- elif cookiecutter.license == "MIT" -%}
license = "MIT"
{%- endif -%}
{%- if cookiecutter.license != "No license file" -%}
license-file = ["LICENSE"]
{%- endif -%}
dependencies = [
    "arcgis>=2.2.0",
    "numpy>=1.7",
    "pandas>=1.0.5",
    "pyarrow>=1.0.0"
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["{{ cookiecutter.support_library }}"]
