[build-system]
requires = ["setuptools>=61.0", "setuptools-scm>=8.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]

name = "{{ cookiecutter.project_name }}"

version = "0.0.0"

authors = [
  { name="{{ cookiecutter.author_name }}"},
]

description = "{{ cookiecutter.description }}"

readme = "README.md"

requires-python = ">=3.9"

classifiers = [
    "Programming Language :: Python :: 3",
]

{% if cookiecutter.open_source_license == "Apache 2.0" %}
license = {text = "Apache-2.0"}
{% elif cookiecutter.open_source_license == "MIT" %}
license = {text = "MIT"}
{% elif cookiecutter.open_source_license == "BSD-3-Clause" %}
license = {text = "BSD-3-Clause"}
{% endif %}

dependencies = [
    "arcgis>=2.2.0",
    "numpy>=1.7",
    "pandas>=1.0.5",
    "pyarrow>=1.0.0",
    # "arcpy-parquet @ git+https://github.com/knu2xs/arcpy-parquet.git",
    
]

[tool.setuptools.packages.find]
where = ["src"]
include = ["{{ cookiecutter.support_library }}*"]

[tool.setuptools.package-data]
"{{ cookiecutter.support_library }}.sql" = ["*.sql"]
